/**
 * Generated by tsnapi — public API snapshot of `monaco-unocss`
 */
// #region Variables
export declare const configureMonacoUnocss: ConfigureMonacoUnocss;
export declare const defaultLanguageSelector: readonly ["css", "javascript", "html", "mdx", "typescript"];
// #endregion

// #region Other
export { UnocssConfig }
// #endregion